-- local rt = require("rust-tools")
local crates = require("crates")

-- local extension_path = vim.env.HOME .. '/.vscode-server/extensions/vadimcn.vscode-lldb-1.9.2/'
-- local codelldb_path = extension_path .. 'adapter/codelldb'
-- local liblldb_path = extension_path .. 'lldb/lib/liblldb'
-- local this_os = vim.loop.os_uname().sysname;
--
-- if this_os:find "Windows" then
--   codelldb_path = package_path .. "adapter\\codelldb.exe"
--   liblldb_path = package_path .. "lldb\\bin\\liblldb.dll"
-- else
--   liblldb_path = liblldb_path .. (this_os == "Linux" and ".so" or ".dylib")
-- end
-- local opts = {
--   hover_actions = {
--     auto_focus = true,
--   },
--   server = {
--     on_attach = function(_, bufnr)
--       -- Hover actions
--       vim.keymap.set("n", "<Leader>c", rt.hover_actions.hover_actions, { buffer = bufnr })
--       -- Code action groups
--       vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
--     end,
--   },
--   dap = {
--     adapter = require('rust-tools.dap').get_codelldb_adapter(
--       codelldb_path, liblldb_path)
--   }
-- }
--
-- rt.setup(opts)
--
crates.setup()
