#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d term web work emacs read zoho misc extra

bspc config border_width        2 
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#bspwm rules
bspc rule -a kitty desktop=term follow=on
bspc rule -a firefox desktop=web follow=on
bspc rule -a zathura desktop=read follow=on
bspc rule -a code desktop=work follow=on
bspc rule -a Ulaa-browser desktop=zoho follow=on
 bspc rule -a Emacs state=fullscreen desktop=emacs follow=on

feh --bg-scale  /home/arvin-ts406/wallpapers/w2.png &
picom &
polybar vbar -r --config=$HOME/.config/polybar/config.ini &

# startup applications
pkill firefox 
xargs -a $HOME/.config/bspwm/zoho_urls.txt  firefox --new-tab "$line" &  emacs --daemon &

bspc config normal_border_color  "#363646"
bspc config active_border_color  "#938AA9G"
bspc config focused_border_color "#938AA9"
